// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: api.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Google.Protobuf.WellKnownTypes
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Api : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"methods")]
        public global::System.Collections.Generic.List<Method> Methods { get; } = new global::System.Collections.Generic.List<Method>();

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public global::System.Collections.Generic.List<Option> Options { get; } = new global::System.Collections.Generic.List<Option>();

        [global::ProtoBuf.ProtoMember(4, Name = @"version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Version { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"source_context")]
        public SourceContext SourceContext { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"mixins")]
        public global::System.Collections.Generic.List<Mixin> Mixins { get; } = new global::System.Collections.Generic.List<Mixin>();

        [global::ProtoBuf.ProtoMember(7, Name = @"syntax")]
        public Syntax Syntax { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Method : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_type_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestTypeUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"request_streaming")]
        public bool RequestStreaming { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"response_type_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResponseTypeUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"response_streaming")]
        public bool ResponseStreaming { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"options")]
        public global::System.Collections.Generic.List<Option> Options { get; } = new global::System.Collections.Generic.List<Option>();

        [global::ProtoBuf.ProtoMember(7, Name = @"syntax")]
        public Syntax Syntax { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Mixin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"root")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Root { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
