// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: type.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Google.Protobuf.WellKnownTypes
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Type : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"fields")]
        public global::System.Collections.Generic.List<Field> Fields { get; } = new global::System.Collections.Generic.List<Field>();

        [global::ProtoBuf.ProtoMember(3, Name = @"oneofs")]
        public global::System.Collections.Generic.List<string> Oneofs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, Name = @"options")]
        public global::System.Collections.Generic.List<Option> Options { get; } = new global::System.Collections.Generic.List<Option>();

        [global::ProtoBuf.ProtoMember(5, Name = @"source_context")]
        public SourceContext SourceContext { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"syntax")]
        public Syntax Syntax { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Field : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Kind kind { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Cardinality cardinality { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"number")]
        public int Number { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"type_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TypeUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"oneof_index")]
        public int OneofIndex { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"packed")]
        public bool Packed { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"options")]
        public global::System.Collections.Generic.List<Option> Options { get; } = new global::System.Collections.Generic.List<Option>();

        [global::ProtoBuf.ProtoMember(10, Name = @"json_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string JsonName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"default_value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DefaultValue { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum Kind
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_UNKNOWN")]
            TypeUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_DOUBLE")]
            TypeDouble = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_FLOAT")]
            TypeFloat = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_INT64")]
            TypeInt64 = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_UINT64")]
            TypeUint64 = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_INT32")]
            TypeInt32 = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_FIXED64")]
            TypeFixed64 = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_FIXED32")]
            TypeFixed32 = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_BOOL")]
            TypeBool = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_STRING")]
            TypeString = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_GROUP")]
            TypeGroup = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_MESSAGE")]
            TypeMessage = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_BYTES")]
            TypeBytes = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_UINT32")]
            TypeUint32 = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_ENUM")]
            TypeEnum = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SFIXED32")]
            TypeSfixed32 = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SFIXED64")]
            TypeSfixed64 = 16,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SINT32")]
            TypeSint32 = 17,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SINT64")]
            TypeSint64 = 18,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Cardinality
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CARDINALITY_UNKNOWN")]
            CardinalityUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CARDINALITY_OPTIONAL")]
            CardinalityOptional = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CARDINALITY_REQUIRED")]
            CardinalityRequired = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"CARDINALITY_REPEATED")]
            CardinalityRepeated = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Enum : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"enumvalue")]
        public global::System.Collections.Generic.List<EnumValue> Enumvalues { get; } = new global::System.Collections.Generic.List<EnumValue>();

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public global::System.Collections.Generic.List<Option> Options { get; } = new global::System.Collections.Generic.List<Option>();

        [global::ProtoBuf.ProtoMember(4, Name = @"source_context")]
        public SourceContext SourceContext { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"syntax")]
        public Syntax Syntax { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnumValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"number")]
        public int Number { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"options")]
        public global::System.Collections.Generic.List<Option> Options { get; } = new global::System.Collections.Generic.List<Option>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Option : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public Any Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Syntax
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SYNTAX_PROTO2")]
        SyntaxProto2 = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SYNTAX_PROTO3")]
        SyntaxProto3 = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
