// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: api.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Rpc
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginUserReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string userName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginUserAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public long userId { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gatewayIp { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gatewayToken { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartBeatReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint RecvAckSynId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint RecvPushSynId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartBeatAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long serverTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserLoginReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long userId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gatewayToken { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public long clientTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserLoginAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReconnectReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long userId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gatewayToken { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public uint ackSynId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint pushSynId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReconnectAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] AckSynIds { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<ReconnectData> AckSynDatas { get; } = new global::System.Collections.Generic.List<ReconnectData>();

        [global::ProtoBuf.ProtoMember(4, IsPacked = true)]
        public uint[] PushSynIds { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<ReconnectData> PushSynDatas { get; } = new global::System.Collections.Generic.List<ReconnectData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReconnectData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public global::System.Collections.Generic.List<byte[]> Datas { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Ack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetInitDataReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long userId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetInitDataAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long userId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public SalesmanData SalesmanData { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"Bluepoint")]
        public global::System.Collections.Generic.List<ClientBluepoint> Bluepoints { get; } = new global::System.Collections.Generic.List<ClientBluepoint>();

        [global::ProtoBuf.ProtoMember(10, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

        [global::ProtoBuf.ProtoMember(11, Name = @"mapdata")]
        public MapInfo Mapdata { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public BagChange initBagChange { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"areaData")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, AreaData> areaDatas { get; } = new global::System.Collections.Generic.Dictionary<int, AreaData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientBluepoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"index")]
        public int Index { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public Bluepoint Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ShopBuyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num")]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ShopBuyAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SalesmanBuyReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public ActionTypeByShop Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SalesmanBuyAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BagChange bagChange { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        public SalesmanData Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SalesmanCutReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public ActionTypeByShop Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SalesmanCutAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public SalesmanData Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SalesmanDisReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SalesmanDisAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SalesmanData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public long Time { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int buyCutNum { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int sellCutNum { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"buyList")]
        public global::System.Collections.Generic.List<Commodity> buyLists { get; } = new global::System.Collections.Generic.List<Commodity>();

        [global::ProtoBuf.ProtoMember(6, Name = @"sellList")]
        public global::System.Collections.Generic.List<Commodity> sellLists { get; } = new global::System.Collections.Generic.List<Commodity>();

        [global::ProtoBuf.ProtoMember(7)]
        public int Disperse { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Commodity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int ProductId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int ProductNum { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int CurrencyId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int CurrencyNum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"context")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Context { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemChangeNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public BagChange Data { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        public ItemChangeType Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BagChange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"bags")]
        public global::System.Collections.Generic.List<ClientBagItem> Bags { get; } = new global::System.Collections.Generic.List<ClientBagItem>();

        [global::ProtoBuf.ProtoMember(2, Name = @"pets")]
        public global::System.Collections.Generic.List<ClientPet> Pets { get; } = new global::System.Collections.Generic.List<ClientPet>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<ClientPetEquip> petEquips { get; } = new global::System.Collections.Generic.List<ClientPetEquip>();

        [global::ProtoBuf.ProtoMember(4, Name = @"build")]
        public global::System.Collections.Generic.List<ClientBuild> Builds { get; } = new global::System.Collections.Generic.List<ClientBuild>();

        [global::ProtoBuf.ProtoMember(5, Name = @"CollectingCabinItem")]
        public global::System.Collections.Generic.List<ClientCollectingCabinItem> CollectingCabinItems { get; } = new global::System.Collections.Generic.List<ClientCollectingCabinItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapOperate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"opr")]
        public UpdateMapOpr Opr { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"point")]
        public Point Point { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateMapReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"opr")]
        public global::System.Collections.Generic.List<MapOperate> Oprs { get; } = new global::System.Collections.Generic.List<MapOperate>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateMapAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        public BagChange Data { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"areaData")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, AreaData> areaDatas { get; } = new global::System.Collections.Generic.Dictionary<int, AreaData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SaveMapReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int SaveIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SaveMapAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"Bluepoint")]
        public global::System.Collections.Generic.List<ClientBluepoint> Bluepoints { get; } = new global::System.Collections.Generic.List<ClientBluepoint>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoadMapReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int LoadIndex { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string exString { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoadMapAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        public BagChange Data { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public MapInfo mapInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockBuildData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"central")]
        public Central Central
        {
            get => __pbn__build.Is(1) ? ((Central)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeCentral() => __pbn__build.Is(1);
        public void ResetCentral() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__build;

        [global::ProtoBuf.ProtoMember(2, Name = @"lottery")]
        public Lottery Lottery
        {
            get => __pbn__build.Is(2) ? ((Lottery)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeLottery() => __pbn__build.Is(2);
        public void ResetLottery() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 2);

        [global::ProtoBuf.ProtoMember(3)]
        public PetConstruct petConstruct
        {
            get => __pbn__build.Is(3) ? ((PetConstruct)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializepetConstruct() => __pbn__build.Is(3);
        public void ResetpetConstruct() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 3);

        [global::ProtoBuf.ProtoMember(4)]
        public PetIncubationCabin petIncubationCabin
        {
            get => __pbn__build.Is(4) ? ((PetIncubationCabin)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializepetIncubationCabin() => __pbn__build.Is(4);
        public void ResetpetIncubationCabin() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 4);

        [global::ProtoBuf.ProtoMember(5)]
        public PetCompetition petCompetition
        {
            get => __pbn__build.Is(5) ? ((PetCompetition)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializepetCompetition() => __pbn__build.Is(5);
        public void ResetpetCompetition() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 5);

        [global::ProtoBuf.ProtoMember(6)]
        public CollectingCabins collectingCabins
        {
            get => __pbn__build.Is(6) ? ((CollectingCabins)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializecollectingCabins() => __pbn__build.Is(6);
        public void ResetcollectingCabins() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 6);

        [global::ProtoBuf.ProtoMember(7)]
        public PetExplore petExplore
        {
            get => __pbn__build.Is(7) ? ((PetExplore)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializepetExplore() => __pbn__build.Is(7);
        public void ResetpetExplore() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 7);

        [global::ProtoBuf.ProtoMember(8)]
        public StarTable starTable
        {
            get => __pbn__build.Is(8) ? ((StarTable)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
        }
        public bool ShouldSerializestarTable() => __pbn__build.Is(8);
        public void ResetstarTable() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 8);

        [global::ProtoBuf.ProtoMember(9, Name = @"warehouse")]
        public Warehouse Warehouse
        {
            get => __pbn__build.Is(9) ? ((Warehouse)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(9, value);
        }
        public bool ShouldSerializeWarehouse() => __pbn__build.Is(9);
        public void ResetWarehouse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 9);

        [global::ProtoBuf.ProtoMember(10, Name = @"workshop")]
        public Workshop Workshop
        {
            get => __pbn__build.Is(10) ? ((Workshop)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(10, value);
        }
        public bool ShouldSerializeWorkshop() => __pbn__build.Is(10);
        public void ResetWorkshop() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 10);

        [global::ProtoBuf.ProtoMember(11, Name = @"decorations")]
        public Decorations Decorations
        {
            get => __pbn__build.Is(11) ? ((Decorations)__pbn__build.Object) : default;
            set => __pbn__build = new global::ProtoBuf.DiscriminatedUnionObject(11, value);
        }
        public bool ShouldSerializeDecorations() => __pbn__build.Is(11);
        public void ResetDecorations() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__build, 11);

        [global::ProtoBuf.ProtoMember(100)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(101)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(102)]
        public int CfgId { get; set; }

        [global::ProtoBuf.ProtoMember(103)]
        public bool Building { get; set; }

        [global::ProtoBuf.ProtoMember(104)]
        public bool Effective { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IncubationPutReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string eggId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IncubationPutAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BlockBuildData blockBuildData { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IncubationPutAllReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IncubationPutAllAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BlockBuildData blockBuildData { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IncubationGetReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"slotId", IsPacked = true)]
        public int[] slotIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IncubationGetAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BlockBuildData blockBuildData { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IncubationQuickReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int slotId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IncubationQuickAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BlockBuildData blockBuildData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotteryMachineReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"num")]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotteryMachineAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public BagChange Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CollectingCabinsPutPetReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"putData")]
        public global::System.Collections.Generic.List<PutData> putDatas { get; } = new global::System.Collections.Generic.List<PutData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PutData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string petId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int slotId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CollectingCabinsPutPetAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BlockBuildData blockBuildData { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CollectingCabinsGetReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CollectingCabinsGetAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CollectingCabinsOffPetReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string petId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CollectingCabinsOffPetAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BlockBuildData blockBuildData { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructPetPutReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"putData")]
        public global::System.Collections.Generic.List<PutData> putDatas { get; } = new global::System.Collections.Generic.List<PutData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructPetPutAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BlockBuildData blockBuildData { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructPetOffReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string petId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructPetOffAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BlockBuildData blockBuildData { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructBuildReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"point")]
        public Point Point { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructBuildAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Point Entity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructBuildFinishReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string finishBuildId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructBuildFinishAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructLevelUpBuildReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string levelUpBuildId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructLevelUpBuildAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructLevelUpBlockReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"point")]
        public global::System.Collections.Generic.List<Point> Points { get; } = new global::System.Collections.Generic.List<Point>();

        [global::ProtoBuf.ProtoMember(3)]
        public int LevelUpBlockCfgId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructLevelUpBlockAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public MapInfo mapInfo { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"areaData")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, AreaData> areaDatas { get; } = new global::System.Collections.Generic.Dictionary<int, AreaData>();

        [global::ProtoBuf.ProtoMember(6, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructLevelUpFinishReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string levelUpBuildId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructLevelUpFinishAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateAllMapReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public MapInfo Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateAllMapAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public MapInfo mapInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructTaskCancelReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string cancelBuildId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConstructTaskCancelAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"blockBuildData")]
        public global::System.Collections.Generic.List<BlockBuildData> blockBuildDatas { get; } = new global::System.Collections.Generic.List<BlockBuildData>();

        [global::ProtoBuf.ProtoMember(3)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarTableUpReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string petId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarTableUpAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarTableReleaseReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string buildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"petId")]
        public global::System.Collections.Generic.List<string> petIds { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarTableReleaseAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAreaInfoReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAreaInfoAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"areaData")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, AreaData> areaDatas { get; } = new global::System.Collections.Generic.Dictionary<int, AreaData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AreaData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"point")]
        public global::System.Collections.Generic.List<Point> Points { get; } = new global::System.Collections.Generic.List<Point>();

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long LastGenReward { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"rewards")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Rewards { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PickItemReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int areaId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public PickType Type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PickItemAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BagChange bagChange { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"areaData")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, AreaData> areaDatas { get; } = new global::System.Collections.Generic.Dictionary<int, AreaData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskDataNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public global::System.Collections.Generic.List<TaskInfo> Datas { get; } = new global::System.Collections.Generic.List<TaskInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int taskId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"state")]
        public int State { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"cond", IsPacked = true)]
        public int[] Conds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskFinishReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int taskId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskFinishAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ErrCode errCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public BagChange bagChange { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum HttpApI
    {
        [global::ProtoBuf.ProtoEnum(Name = @"none")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"login")]
        Login = 10,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ProtoId
    {
        HeartBeat = 0,
        UserLogin = 1,
        Reconnect = 2,
        GameStartId = 10000,
        GetInitData = 10001,
        ShopBuy = 10002,
        SalesmanBuy = 10003,
        SalesmanCut = 10004,
        SalesmanDis = 10005,
        Gm = 10101,
        ItemChange = 10201,
        UpdateMap = 10300,
        SaveMap = 10301,
        LoadMap = 10302,
        UpdateAllMap = 10303,
        IncubationPut = 10401,
        IncubationGet = 10402,
        IncubationQuick = 10403,
        IncubationPutAll = 10404,
        LotteryMachine = 10501,
        CollectingCabinsPutPet = 10601,
        CollectingCabinsOffPet = 10602,
        CollectingCabinsGet = 10603,
        ConstructPetPut = 10701,
        ConstructPetOff = 10702,
        ConstructBuild = 10703,
        ConstructBuildFinish = 10704,
        ConstructLevelUpBlock = 10705,
        ConstructLevelUpBuild = 10706,
        ConstructLevelUpFinish = 10707,
        ConstructTaskCancel = 10708,
        StarTableUp = 10801,
        StarTableRelease = 10802,
        GetAreaInfo = 10901,
        PickItem = 10902,
        TaskData = 11001,
        TaskFinish = 11002,
        GameEndId = 19999,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ActionTypeByShop
    {
        Buy = 0,
        Sell = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ItemChangeType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"GM")]
        Gm = 0,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum UpdateMapOpr
    {
        AddBlock = 0,
        RemBlock = 1,
        AddEntity = 2,
        RemEntity = 3,
        MoveEntity = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PickType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PET")]
        Pet = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HAND")]
        Hand = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
