// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: data.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Rpc
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientBagItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int BaseId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientPet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int BaseId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Num { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"data")]
        public ClientPetData Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientPetEquip : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int BaseId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientBuild : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int BaseId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Num { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientCollectingCabinItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int BaseId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientCollectingCabinPet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int BaseId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Num { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientConstructPet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int BaseId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Num { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientPetData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attribute")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, Attribute> Attributes { get; } = new global::System.Collections.Generic.Dictionary<int, Attribute>();

        [global::ProtoBuf.ProtoMember(2, Name = @"Skill", IsPacked = true)]
        public int[] Skills { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Mood { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int Tired { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int Exp { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int Gender { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string WorkBuildId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Attribute : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Value { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int EffortValue { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int PercentValue { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int OtherValue { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int FinalValue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Bluepoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public MapInfo Data { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long saveTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Point> Entities { get; } = new global::System.Collections.Generic.List<Point>();

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<Point> Blocks { get; } = new global::System.Collections.Generic.List<Point>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Point : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int CfgId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int Y { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Central : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Lottery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long LastTakeTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int Combo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PetConstruct : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"Slot")]
        public global::System.Collections.Generic.List<string> Slots { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"TaskList")]
        public global::System.Collections.Generic.List<Task> TaskLists { get; } = new global::System.Collections.Generic.List<Task>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Task : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public TaskType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string BuildId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public long StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long EndTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PetIncubationCabin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"Slot")]
        public global::System.Collections.Generic.List<PetIncubationCabinSlotData> Slots { get; } = new global::System.Collections.Generic.List<PetIncubationCabinSlotData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PetIncubationCabinSlotData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long PutTime { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long EndTime { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int PetCfg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PetCompetition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CollectingCabins : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"Slot")]
        public global::System.Collections.Generic.List<string> Slots { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2)]
        public int AreaLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PetExplore : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StarTable : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Warehouse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Workshop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Decorations : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DbArea : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"Area")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, DbAreaData> Areas { get; } = new global::System.Collections.Generic.Dictionary<int, DbAreaData>();

        [global::ProtoBuf.ProtoMember(2, Name = @"pointData")]
        public global::System.Collections.Generic.List<DbPointData> pointDatas { get; } = new global::System.Collections.Generic.List<DbPointData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DbPointData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Point Point { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int AreaI { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"Reward")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Rewards { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DbAreaData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long LastTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StatisticsCondEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public EventType EventType { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public SCBlock SCBlock { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public SCBuild SCBuild { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public SCItem SCItem { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public SCPet SCPet { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public SCLottery SCLottery { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public SCLook SCLook { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public SCBuildPet SCBuildPet { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public SCLevelUpBlock SCLevelUpBlock { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public SCLevelUpBuild SCLevelUpBuild { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCBlock : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Block { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"BlockCond")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> BlockConds { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCBuild : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"BuildCond")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> BuildConds { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ItemGet")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> ItemGets { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCPet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Num { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"PetGet")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> PetGets { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCLottery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCLook : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCLevelUpBlock : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"Cond")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Conds { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCLevelUpBuild : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"Cond")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Conds { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SCBuildPet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"Cond")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, int> Conds { get; } = new global::System.Collections.Generic.Dictionary<int, int>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum TaskType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LEVELUP")]
        Levelup = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BUILD")]
        Build = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EventType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ET_BLOCK")]
        EtBlock = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ET_BUILD")]
        EtBuild = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ET_ITEM")]
        EtItem = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ET_PET")]
        EtPet = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ET_LOTTERY")]
        EtLottery = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"ET_LOOK")]
        EtLook = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"ET_BUILDPET")]
        EtBuildpet = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"ET_LEVELUPBLOCK")]
        EtLevelupblock = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"ET_LEVELUPBUILD")]
        EtLevelupbuild = 11,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
