// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: plugin.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace google.protobuf.compiler
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Version : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"major")]
        public int Major
        {
            get => __pbn__Major.GetValueOrDefault();
            set => __pbn__Major = value;
        }
        public bool ShouldSerializeMajor() => __pbn__Major != null;
        public void ResetMajor() => __pbn__Major = null;
        private int? __pbn__Major;

        [global::ProtoBuf.ProtoMember(2, Name = @"minor")]
        public int Minor
        {
            get => __pbn__Minor.GetValueOrDefault();
            set => __pbn__Minor = value;
        }
        public bool ShouldSerializeMinor() => __pbn__Minor != null;
        public void ResetMinor() => __pbn__Minor = null;
        private int? __pbn__Minor;

        [global::ProtoBuf.ProtoMember(3, Name = @"patch")]
        public int Patch
        {
            get => __pbn__Patch.GetValueOrDefault();
            set => __pbn__Patch = value;
        }
        public bool ShouldSerializePatch() => __pbn__Patch != null;
        public void ResetPatch() => __pbn__Patch = null;
        private int? __pbn__Patch;

        [global::ProtoBuf.ProtoMember(4, Name = @"suffix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Suffix
        {
            get => __pbn__Suffix ?? "";
            set => __pbn__Suffix = value;
        }
        public bool ShouldSerializeSuffix() => __pbn__Suffix != null;
        public void ResetSuffix() => __pbn__Suffix = null;
        private string __pbn__Suffix;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CodeGeneratorRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"file_to_generate")]
        public global::System.Collections.Generic.List<string> FileToGenerates { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"parameter")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Parameter
        {
            get => __pbn__Parameter ?? "";
            set => __pbn__Parameter = value;
        }
        public bool ShouldSerializeParameter() => __pbn__Parameter != null;
        public void ResetParameter() => __pbn__Parameter = null;
        private string __pbn__Parameter;

        [global::ProtoBuf.ProtoMember(15, Name = @"proto_file")]
        public global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.FileDescriptorProto> ProtoFiles { get; } = new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.FileDescriptorProto>();

        [global::ProtoBuf.ProtoMember(3, Name = @"compiler_version")]
        public Version CompilerVersion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CodeGeneratorResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Error
        {
            get => __pbn__Error ?? "";
            set => __pbn__Error = value;
        }
        public bool ShouldSerializeError() => __pbn__Error != null;
        public void ResetError() => __pbn__Error = null;
        private string __pbn__Error;

        [global::ProtoBuf.ProtoMember(2, Name = @"supported_features")]
        public ulong SupportedFeatures
        {
            get => __pbn__SupportedFeatures.GetValueOrDefault();
            set => __pbn__SupportedFeatures = value;
        }
        public bool ShouldSerializeSupportedFeatures() => __pbn__SupportedFeatures != null;
        public void ResetSupportedFeatures() => __pbn__SupportedFeatures = null;
        private ulong? __pbn__SupportedFeatures;

        [global::ProtoBuf.ProtoMember(15, Name = @"file")]
        public global::System.Collections.Generic.List<File> Files { get; } = new global::System.Collections.Generic.List<File>();

        [global::ProtoBuf.ProtoContract()]
        public partial class File : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name
            {
                get => __pbn__Name ?? "";
                set => __pbn__Name = value;
            }
            public bool ShouldSerializeName() => __pbn__Name != null;
            public void ResetName() => __pbn__Name = null;
            private string __pbn__Name;

            [global::ProtoBuf.ProtoMember(2, Name = @"insertion_point")]
            [global::System.ComponentModel.DefaultValue("")]
            public string InsertionPoint
            {
                get => __pbn__InsertionPoint ?? "";
                set => __pbn__InsertionPoint = value;
            }
            public bool ShouldSerializeInsertionPoint() => __pbn__InsertionPoint != null;
            public void ResetInsertionPoint() => __pbn__InsertionPoint = null;
            private string __pbn__InsertionPoint;

            [global::ProtoBuf.ProtoMember(15, Name = @"content")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Content
            {
                get => __pbn__Content ?? "";
                set => __pbn__Content = value;
            }
            public bool ShouldSerializeContent() => __pbn__Content != null;
            public void ResetContent() => __pbn__Content = null;
            private string __pbn__Content;

            [global::ProtoBuf.ProtoMember(16, Name = @"generated_code_info")]
            public global::Google.Protobuf.Reflection.GeneratedCodeInfo GeneratedCodeInfo { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Feature
        {
            [global::ProtoBuf.ProtoEnum(Name = @"FEATURE_NONE")]
            FeatureNone = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"FEATURE_PROTO3_OPTIONAL")]
            FeatureProto3Optional = 1,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
